<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- <TargetFramework>net481</TargetFramework> -->
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- <Nullable>enable</Nullable> -->
  </PropertyGroup>
  <ItemGroup />

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <MakeDir Directories="$(TargetDir)x86;$(TargetDir)x64" />
    <Copy SourceFiles="$(ProjectDir)..\dependencies\x86\interception.dll" DestinationFolder="$(TargetDir)x86" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(ProjectDir)..\dependencies\x64\interception.dll" DestinationFolder="$(TargetDir)x64" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <MakeDir Directories="$(ProjectDir)..\..\Lib" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\..\Lib" SkipUnchangedFiles="true" />
  </Target>
</Project>